services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-bookstore
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    environment: 
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY='django-insecure-mfal^@4r3=vbj(pfgrpftvq59el5j4m+p*aas(c=dqiy1z*%sk'
      - DJANGO_DEBUG=True
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJNAGO_SECURE_HSTS_SECONDS=0
      - DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False
      - DJANGO_SECURE_HSTS_PRELOAD=False
      - DJANGO_SESSION_COOKIE_SECURE=False
      - DJANGO_CSRF_COOKIE_SECURE=False
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:  # Corrected here
      POSTGRES_HOST_AUTH_METHOD: trust 

volumes:
  postgres_data:
