services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-bookstore
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:  # Corrected here
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY='django-insecure-mfal^@4r3=vbj(pfgrpftvq59el5j4m+p*aas(c=dqiy1z*%sk'
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:  # Corrected here
      POSTGRES_HOST_AUTH_METHOD: trust 

volumes:
  postgres_data:
