services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-bookstore
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000  
    environment:  # Corrected here
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY='R1hdOWIbjCDFeE7_Ws2tXgy_ikrjukliL80TBukXF7M2-0JBxRM'
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:  # Corrected here
      POSTGRES_HOST_AUTH_METHOD: trust 

volumes:
  postgres_data:
